# Build image
FROM golang:1.10.3 as BUILD

WORKDIR /go/src/github.com/btcsuite/btcd
COPY . .

RUN go get -u github.com/Masterminds/glide
RUN glide install
RUN CGO_ENABLED=0 GOOS=linux go install

# Production image
FROM alpine:latest as PRODUCT

RUN apk add --no-cache ca-certificates
COPY --from=0 /go/bin/* /bin/

EXPOSE 8333
EXPOSE 8334

CMD btcd --connect=207.148.66.91 --rpcuser=a --rpcpass=a --notls --rpclisten=:8334
